name: CMake + Conan CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Установка Conan
      run: pip install conan==2.16.1

    - name: Инициализация Conan
      run: conan profile detect --force

    - name: Установка зависимостей через Conan
      run: |
        conan install . \
          --output-folder=build \
          --build=missing \
          -s build_type=${{ matrix.build_type }} \
          -s compiler=${{ matrix.c_compiler }}

    - name: Преобразование build_type в нижний регистр
      run: echo "BUILD_TYPE_LOWER=$(echo '${{ matrix.build_type }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Сборка проекта с использованием CMake Presets
      run: |
        cmake --preset conan-${BUILD_TYPE_LOWER}
        cmake --build --preset conan-${BUILD_TYPE_LOWER}

    - name: Запуск тестов
      run: ctest --preset conan-${BUILD_TYPE_LOWER}

